//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTLBlog
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Blog()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public int BlogId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> Blogdanhmuc { get; set; }
        public string BlogTitle { get; set; }
        public string BlogContent { get; set; }
        public Nullable<System.DateTime> BlogCreatedDate { get; set; }
        public Nullable<int> Bloglike { get; set; }
        public Nullable<int> BlogComments { get; set; }
    
        public virtual Danhmuc Danhmuc { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
    }
}
