//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTLBlog
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiDanhmuc
    {
        public int LoaiDanhmucId { get; set; }
        public Nullable<int> DanhmucId { get; set; }
        public string TenLoai { get; set; }
        public string MaLoai { get; set; }
    
        public virtual Danhmuc Danhmuc { get; set; }
    }
}
