//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTLBlog
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preference
    {
        public int PreferenceId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Setting { get; set; }
        public string Value { get; set; }
    
        public virtual User User { get; set; }
    }
}
